name: App Build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create Placeholder file
        run: echo "keystorePath='' keystorePass='' keyAlias='' keyPass=''" > ./keystore.properties

      - name: Decode GCP_KEY
        env:
          GCP_SERVICES: ${{secrets.GCP_KEY}}
        run: echo "$GCP_SERVICES" > team2059-scouting-android/app/src/google-services.json

      - name: Run Tests
        run: ./gradlew test


      - name: Build Project
        run: ./gradlew assemble

