name: App Build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Create Placeholder file
        run: echo "" > ./keystore.properties

      - name: Run Tests
        run: ./gradlew test


      - name: Build Project
        run: ./gradlew assemble

